---

name: Release

on:
  # Triggers the workflow on push or pull request events
  release:
    tags:
      - 'v*'
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Client_build:
    name: Client build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # # Setup tmate session
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: install composer
        run: sudo apt-get install -y composer wget

      - name: Lint code
        run: |
          cd ..
          mkdir CodeSniffer
          cd CodeSniffer
          echo '{}' > composer.json
          composer config -n allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer require woocommerce/woocommerce-sniffs -n --dev
          wget https://gist.github.com/woogists/d7da244ebad9a86286ad344a394c61ff/raw/c10cc6a18fcff0127b5535dcea5fe4c9ef27238a/phpcs.xml
          ./vendor/bin/phpcs \
          --standard=WooCommerce-Core,phpcs.xml \
          --warning-severity=0 \
          -s \
          -v \
          --ignore-annotations \
          --extensions=php,html \
          --ignore=*/assets/*,*/build/*,*/dist/*,*/node_modules/*,*/src/*,*/vendor/* \
          ../student-discount-for-woocommerce

      - name: Create zip file
        run: |
          cd ..
          zip -r /tmp/student-discount-for-woocommerce.zip student-discount-for-woocommerce -x \
          *\.git* \
          */vendor/paragonie/random_compat/build-phar.sh \
          @

      - name: Show what we are shipping
        run: |
          unzip -t /tmp/student-discount-for-woocommerce.zip

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: student-discount-for-woocommerce
          path: /tmp/student-discount-for-woocommerce.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/student-discount-for-woocommerce.zip
