---

name: Release

on:
  # Triggers the workflow on push or pull request events
  release:
    tags:
      - 'v*'
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Client_build:
    name: Client build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          zip -r /tmp/student-discount-for-woocommerce.zip student-discount-for-woocommerce -x *\.git* @

      - name: Show what we are shipping
        run: |
          unzip -t student-discount-for-woocommerce.zip

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: student-discount-for-woocommerce
          path: /tmp/student-discount-for-woocommerce.zip


  Artifact_upload:
    name: Create release
    needs:
      - "Client_build"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch build
        id: fetch_artifact
        uses: actions/download-artifact@v4
        with:
          name: student-discount-for-woocommerce
          path: artifacts/

      - name: Create Release
        if: "github.ref_type=='tag'"
        uses: softprops/action-gh-release@v2
        with:
          files: "${{steps.fetch_artifact.outputs.download-path}}/*"

